fitnessWebApp/fitnessWebApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views

urlpatterns = [
    path('', views.about, name='about'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  

fitnessWebApp/rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.about, name='about'),
    path('loggedIn/', views.homePage, name='homePage'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('activities/', views.activities, name='activities'),
    path('activities/autocomplete/', views.auto_complete_function, name='auto_complete_function'),
    path('activities/activity_process/', views.activity_process, name='activity_process'),
    path('activities/filter_activities/', views.filter_activities, name='filter_activities'),
    path('nutrition/', views.nutrition, name='nutrition'),
    path('nutrition/create/', views.meal_process, name='meal_process'),
    path('report/', views.report, name='report'),    
]

fitnessWebApp/rango/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from rango.models import  Food, Profile_food, UserProfile, ActivityCategory, Activities

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class SelectExerciseForm(forms.ModelForm):
    Intensity_estimator = forms.ModelChoiceField(queryset=Activities.objects.all().order_by('api_description'))
    Description = forms.CharField(max_length=256, required=False, label='Describe your activity (optional)')
    Time_in_min = forms.IntegerField(min_value=0)
    class Meta:
        model = Activities
        fields = ('activity_category',)

class SelectExerciseSearchForm(forms.ModelForm):
    Description = forms.CharField(max_length=256, required=False, label='Describe your activity (optional)')
    Time_in_min = forms.IntegerField(min_value=0)
    class Meta:
        model = Activities
        fields = ('api_description', )
    def __init__(self, *args, **kwargs):
        super(SelectExerciseSearchForm, self).__init__(*args, **kwargs)
        self.fields['api_description'].label = 'Search in Database'

class SelectFoodForm(forms.ModelForm):
    class Meta:
        model = Profile_food
        fields = ('meal',)

class AddFoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ('name',)

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile_food
        fields = ('calorie_goal',)
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['calorie_goal'].label = 'Calorie Goal (optional):'

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('gender', 'goal', 'age', 'weight', 'height',)
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['weight'].label = 'weight in kg'
        self.fields['height'].label = 'height in cm'

fitnessWebApp/rango/views.py
# from django.contrib.auth.models import User
from django.http.response import JsonResponse
# from django.views import View
from django.shortcuts import render, redirect
from django.conf import settings
from django.core.files.storage import default_storage
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rango.models import Activities, ActivityCategory, Profile_food, Profile_activity, PostFood, UserProfile, PostActivities
from rango.forms import UserForm, UserProfileForm, ProfileForm, SelectExerciseForm, SelectExerciseSearchForm
from rango import api_keys
# from django.utils import timezone
from datetime import date, datetime, timedelta
# from django.db import connections
import json, requests, random
# import tensorflow.compat.v1 as tf
import numpy as np
# from keras import backend as K
from keras.applications import vgg16
from keras.applications.imagenet_utils import decode_predictions
from keras.preprocessing.image import img_to_array, load_img
from tensorflow.python.keras.backend import set_session
from django.views.decorators.csrf import csrf_exempt
from django.utils.datastructures import MultiValueDictKeyError

url_food_database = "https://api.edamam.com/api/food-database/v2/parser"

url_nutrition_analysis = "https://api.edamam.com/api/nutrition-data"

def about(request):
    logout(request)
    return render(request, 'rango/about.html')

## Home page for stating the user's information - daily calories consumed, daily macros consumed
def homePage(request):
    print('Home Page')
    context_dict = {}
    
    ##If user is authenticated - extract all the infos necessary
    if request.user.is_authenticated:
        loggedInUser_food = Profile_food.objects.filter(person=request.user).last()     ##Fetch Database for the food Profile of the user
        calories = loggedInUser_food.calorie_goal       ##extract the calorie goal

        ##Update the Profile on a daily - each day is a new record
        if date.today() != loggedInUser_food.date_today:
            print("Date is different -> Creating new Profile for this date")
            newProfile = Profile_food.objects.create(
                person=request.user, calorie_goal=calories)
            newProfile.save()
            newProfile = Profile_activity.objects.create(
                person=request.user
            )
            newProfile.save()

        ##Fetch the Database for the newest food Profile of the user
        loggedInUser_food = Profile_food.objects.filter(person=request.user).last()

        calories_consumed = loggedInUser_food.calorie_consumed_day
        calorie_goal = loggedInUser_food.calorie_goal
        
        ##extracting macros consumed for the day
        nutrients = Profile_food.objects.filter(person=request.user) \
            .values('protein_consumed_day', 'carbs_consumed_day', 'fats_consumed_day') \
            .last()

        ##JSON for the macros to use them in Javascript
        nutrients_dict = [   
                            {'name': 'protein', 'value': nutrients['protein_consumed_day']},
                            {'name': 'carbs', 'value': nutrients['carbs_consumed_day']},
                            {'name': 'fats', 'value': nutrients['fats_consumed_day']}
                        ]
        nutrients_json = json.dumps(nutrients_dict)
        
        ##JSON for the calories to use them in the Javascript
        calories_dict = [   
                            {'name': 'calorie goal', 'value': calorie_goal, 'filler': 'orange'},
                            {'name': 'calories consumed', 'value': calories_consumed, 'filler': 'green'}
                        ]
        calories_json = json.dumps(calories_dict)

        context_dict['nutrients_info'] = nutrients_json
        context_dict['calories_info'] = calories_json
        
        print('nutrients:') 
        print(nutrients_json)

        print('calories')
        print(calories_json)

    return render(request, 'rango/homePage.html', context=context_dict)


##User Login for authenticating the user
def user_login(request):
    print('login')
    context_dict = {}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        
        ##if user is authenticated
        if user:
            ##check if the account is active or disabled
            if user.is_active:
                login(request, user)
                print('Welcome!', user)
                return redirect(reverse('rango:homePage'))
            else:
                print('account is disabled')
                return HttpResponse("Your account is disabled.")
        ##invalid login
        else:
            context_dict['error'] = 'Invalid Login!'
            print('Invalid Login')
            
    return render(request, 'rango/login.html', context=context_dict)


##User logging out
def user_logout(request):
    print('Logging out...')
    logout(request)
    return redirect(reverse('rango:about'))


##User register
def register(request):
    print('Register')
    registered = False
    context_dict = {}
    
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        user_profile_form = UserProfileForm(request.POST)
        profile_form = ProfileForm(request.POST)

        ##Check if everything filled is valid
        if user_form.is_valid() and user_profile_form.is_valid() and profile_form.is_valid():
            print("Everything is valid -> saving...")

            ##Calculating BMR
            if request.POST['gender'] == 'male':
                BMR = int(88.362 + 
                         (13.397 * float(request.POST['weight'])) + 
                         (4.799 * float(request.POST['height'])) - 
                         (5.677 * float(request.POST['age']))
                         )
            ##Female
            else:
                BMR = int(447.593 + 
                         (9.247 * float(request.POST['weight'])) + 
                         (3.098 * float(request.POST['height'])) - 
                         (4.330 * float(request.POST['age']))
                         )

            ##Saving profiles - UserProfile, User, Profile_Food, Profile_Activity
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            userProfile = user_profile_form.save(commit=False)
            userProfile.user = user
            userProfile.BMR = BMR
            userProfile.save()

            profile_food = profile_form.save(commit=False)
            profile_food.person = user
            
            Profile_activity.objects.create(person=user)

            ##If user did not choose a custom calorie goal
            if request.POST['calorie_goal'] == '0' or request.POST['calorie_goal'] == '':
                print('User has not chosen a custom calorie goal -> calculating one')
                ##If User has chosen BULK
                if request.POST['goal'] == 'bulk':
                    cal_goal = BMR + (0.15 * BMR)
                ##If User has chosen MAINTENANCE
                elif request.POST['goal'] == 'maintenance':
                    cal_goal = BMR
                ##If User has Chosen FAT LOSS
                else:
                    cal_goal = BMR - 500

                profile_food.calorie_goal = cal_goal

            profile_food.save()

            info_user_profile = UserProfile.objects.get(user=user)
            info_profile_food = Profile_food.objects.get(person=user)

            ##User Successfully registered
            registered = True

            context_dict['BMR'] = BMR
            print('BMR:', BMR)

            context_dict['age'] = info_user_profile.age
            print('age:', info_user_profile.age)

            context_dict['weight'] = info_user_profile.weight
            print('weight:', info_user_profile.weight)

            context_dict['height'] = info_user_profile.height
            print('height:', info_user_profile.height)

            context_dict['BMI'] = info_user_profile.BMI
            print('BMI:', info_user_profile.BMI)

            context_dict['calorie_goal'] = info_profile_food.calorie_goal
            print('calorie goal:', info_profile_food.calorie_goal)

        ##Error in registering - Invalid field somewhere for instance
        else:
            print('Error while registering!')
            print(user_form.errors, profile_form.errors,
                  user_profile_form.errors)
    ##Displaying Forms for Registering
    else:
        print('Displaying Forms')
        user_form = UserForm()
        user_profile_form = UserProfileForm()
        profile_form = ProfileForm()

    return render(request, 'rango/register.html', context={'user_form': user_form,
                                                           'profile_form': profile_form,
                                                           'user_profile_form': user_profile_form,
                                                           'registered': registered,
                                                           'info': context_dict})

##Profile page - Displays the user's information and allow the user to edit their info
def profile(request):
    print('Profile Page')
    context_dict = {}

    user_profile = UserProfile.objects.get(user=request.user) 

    ##Get the latest Food Profile for the user - calorie_goal
    profile_food = Profile_food.objects.filter(person=request.user) \
        .values('calorie_goal') \
        .last()

    context_dict['gender'] = user_profile.gender
    print('gender', user_profile.gender)

    context_dict['BMR'] = user_profile.BMR
    print('BMR:', user_profile.BMR)

    context_dict['BMI'] = user_profile.BMI
    print('BMI:', user_profile.BMI)

fitnessWebApp/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
    <div class="nav z-depth-0">
        <div class="section center">
            <h3 class="white-text center">- Human Diary for a Healthy Lifestyle -</h3>
        </div>
        <div class="progress"> </div>
    </div>



    <div class="intro">
        <p class="paragraph"> This Website is used to <span class="highlighted-text">track </span> 
                            your<span class="highlighted-text"> Calories</span> 
                            and your <span class="highlighted-text"> Activities. </span>
                            You will see <span class="highlighted-text">pie charts </span>
                            describing your daily activities as well as macros taken during the day. 
                            In addition,  you will have the chance to see a
                            <span class="highlighted-text"> Weekly Report</span> 
                            that grants you the chance for a better visualisation on your weekly consumed 
                            macros in detail using a <span class="highlighted-text">user-interactive graph.</span>
        </p> 
    </div>

    <div class="split left">
        <div class="centered">
        <a href="{% url 'rango:register' %}">Sign Up</a>
        </div>
    </div>
    
    <div class="split right">
        <div class="centered">
        <a href="{% url 'rango:login' %}">Login</a>
        </div>
    </div>

    <div class="footer">
        <div class="progress"> </div>
    </div>
{% endblock %}

fitnessWebApp/templates/rango/activities.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
    <div class="nav z-depth-0">
        <div class="section center">
            <div class="header">
                <a href="{% url 'rango:homePage' %}"><span class="left">Home</span></a>
                <a href="{% url 'rango:logout' %}"><span class="right">Log Out</span></a>
            </div>
            <h3 class="white-text center">- Activities -</h3>
        </div>
    </div>

    <div class="section center">
        <p class="grey-text flow-text">Log your activity by filling the form <span class="highlighted-text">OR</span>
                                       search directly in our database<br />
                                       If you are a beginner user of <span class="highlighted-text">MyFitDiary </span>
                                       fill out the form on the left
        </p>
    </div>
    
    <div class="form-section">
        <div class="activity-check-left">
            {% if user.is_authenticated %}
            <form class="activity-form" id="activity_post_form" method="post" action= "{% url 'rango:activity_process' %}">
                {% csrf_token %}
                {{ ActivityForm }}
                <input type="submit" name="submit" value="Enter" />
            </form>
            {% endif %}
        </div>

        <div class="activity-check-right right">
            {% if user.is_authenticated %}
            <form class="activity-search-form" id="activity_search_form" method="post" action= "{% url 'rango:activity_process' %}">
                {% csrf_token %}
                {{ ActivitySearchForm }}
                <input type="submit" name="submit" value="Enter" />
            </form>
            {% endif %}
        </div>
    </div>
    {% if error %}
        <div class="error-exercises">
            <p class="paragraph center">{{ error }}</p>
        </div>
    {% endif %}

    {% if suggestions %}
        <div class="suggestions left">
            <span class="text">Suggestions:</span>
            {% for suggestion in suggestions %}
                <span class="sug"><span class="highlighted-text">Activity name: </span>{{ suggestion.activity }} , 
                                  <span class="highlighted-text">MET: </span>{{ suggestion.MET }} , 
                                  <span class="highlighted-text">Duration: </span>{{suggestion.Time }} , 
                                  <span class="highlighted-text">Estimated Calories Burned: </span>{{ suggestion.Calories_burned }}
                    <br />
                </span>
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="figure center"></div>
    
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>var activities = {{ activities_info | safe}};</script>
    <script src="{% static 'js/pie_chart_activity.js' %}"></script>
    <script src="{% static 'js/filter_activity.js' %}"></script>
    <script src="{% static 'js/autocomplete.js' %}"></script>
{% endblock %}

fitnessWebApp/templates/rango/calories.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
    <div class="nav z-depth-0">
        <div class="section center">
            <div class="header">
                <a href="{% url 'rango:homePage' %}"><span class="left">Home</span></a>
                <a href="{% url 'rango:logout' %}"><span class="right">Log Out</span></a>
            </div>
            <h3 class="white-text center">- Nutrition -</h3>
        </div>
    </div>

    <div class="section center">
        <p class="grey-text flow-text">Log your meal by <span class="highlighted-text">Text</span>
                                       or <span class="highlighted-text">Photo. </span>
                                       Your meal will be <span class="highlighted-text">Analysed</span> 
                                       and you will get meal <span class="highlighted-text">suggestions</span>
                                       based on the meal you have entered
        </p>
    </div>
    
    <div class="figures-pos-right right">
        <div class="table-data" id="my-data">
            <b><span class="table-text">Meals taken</span></b>
            <table id="my-Table" border="1" cellpadding="2">
                <thead>
                    <tr>
                        <th><b><span class="table-text">Meal</span></b></th>
                        <th><b><span class="table-text">Protein</span></b></th>
                        <th><b><span class="table-text">Carbs</span></b></th>
                        <th><b><span class="table-text">Fat</span></b></th>
                        </tr>
                </thead>
            </table>
        </div>
    </div>


    <div class="form-meal">
        <form id="meal_input" method="post">
            {% csrf_token %}
            <span class="input-text"> Meal: </span>
            <input class="meal" placeholder="Example: 200 gr pasta" id="meal-input" type="text" name="meal" size="20" />
            <input type="submit" name="submit" value="Enter" />
        </form>
        <div class="error-meal" id="error"></div>
        <div id="edamam-badge" data-color="white"></div>
    </div>

    <div class="form-meal-upload">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <span class="input-text">Upload image here:</span>
            <input class="meal-upload" type="file" name="imageFile" />
            <input type="submit" name="submit" value="Upload" />
        </form>
        <div class="error-meal-upload" id="error-upload">
            {%if error %}
                <p class=paragraph center>{{ error }}</p>
            {% endif %}
        </div>
    </div>

    <div class="meals-suggestions">
        <div class="meal-name">
            <span id ="last_meal_name" class="text">Last Meal:</span> 
            <span id ="last_meal_name_value" class="highlighted-text"></span><br />
            <span id="last_meal_status" class="text">Status:</span>
            <span id ="last_meal_status_value" class="highlighted-text"></span>
        </div>
        <div class="figures-pos-left">
            <div class="table-data" id="meal-suggest">
                <b><span class="table-text">Suggestions</span></b>
                <table id="meal-suggestions" border="1" cellpadding="2">
                    <thead>
                        <th><b><span class="table-text">Meal</span></b></th>
                        <th><b><span class="table-text">Protein</span></b></th>
                        <th><b><span class="table-text">Carbs</span></b></th>
                        <th><b><span class="table-text">Fat</span></b></th>
                        <th><b><span class="table-text">Quantity</span></b></th>
                    </thead>
                </table>
            </div>
        </div>
    </div>

    {% if meals %}
        <script> var meals_taken = {{ meals | safe }};</script>
    {% endif %}
    {% if food_sug %}
        <script> var meal_sug = {{ food_sug | safe }};</script>
    {% endif %}
    {% if last_meal %}
        <script> var last_meal = {{ last_meal | safe }}; 
                 var protein_flag = {{ high_protein_flag | safe }};
                 var carb_flag = {{ high_carb_flag }};
                 var fat_flag = {{ high_fat_flag }};
        </script>
    {% endif %}
    <script src="{% static 'js/table.js' %}"></script>
    <script src = "{% static 'js/table_ajax.js' %}"></script> 
    
    
              
{% endblock %}

fitnessWebApp/templates/rango/exercises.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
    <div class="nav z-depth-0">
        <div class="section center">
            <div class="header">
                <a href="{% url 'rango:homePage' %}"><span class="left">Home</span></a>
                <a href="{% url 'rango:logout' %}"><span class="right">Log Out</span></a>
            </div>
            <h3 class="white-text center">- Activities -</h3>
        </div>
    </div>

    <div class="section center">
        <p class="grey-text flow-text">Log your activity by filling the form <span class="highlighted-text">OR</span>
                                       search directly in our database<br />
                                       If you are a beginner user of <span class="highlighted-text">MyFitDiary </span>
                                       fill out the form on the left
        </p>
    </div>
    
    <div class="form-section">
        <div class="activity-check-left">
            {% if user.is_authenticated %}
            <form class="activity-form" id="activity_post_form" method="post" action= "{% url 'rango:activity_process' %}">
                {% csrf_token %}
                {{ ActivityForm }}
                <input type="submit" name="submit" value="Enter" />
            </form>
            {% endif %}
        </div>

        <div class="activity-check-right right">
            {% if user.is_authenticated %}
            <form class="activity-search-form" id="activity_search_form" method="post" action= "{% url 'rango:activity_process' %}">
                {% csrf_token %}
                {{ ActivitySearchForm }}
                <input type="submit" name="submit" value="Enter" />
            </form>
            {% endif %}
        </div>
    </div>
    {% if error %}
        <div class="error-exercises">
            <p class="paragraph center">{{ error }}</p>
        </div>
    {% endif %}

    {% if suggestions %}
        <div class="suggestions left">
            <span class="text">Suggestions:</span>
            {% for suggestion in suggestions %}
                <span class="sug"><span class="highlighted-text">Activity name: </span>{{ suggestion.activity }} , 
                                  <span class="highlighted-text">MET: </span>{{ suggestion.MET }} , 
                                  <span class="highlighted-text">Duration: </span>{{suggestion.Time }} , 
                                  <span class="highlighted-text">Estimated Calories Burned: </span>{{ suggestion.Calories_burned }}
                    <br />
                </span>
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="figure center"></div>
    
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>var activities = {{ activities_info | safe}};</script>
    <script src="{% static 'js/pie_chart_activity.js' %}"></script>
    <script src="{% static 'js/filter_activity.js' %}"></script>
    <script src="{% static 'js/autocomplete.js' %}"></script>
{% endblock %}

fitnessWebApp/templates/rango/homePage.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
    <div class="nav z-depth-0">
        <div class="section center">
            <h3 class="white-text center">- Welcome {{ user.username }} -</h3>
        </div>
    </div>

    <div class="progress"></div>
        {% comment %}    
        <li><a href="{% url 'rango:BMI' %}">Fat Percentage</a></li> 
        <li><a href="{% url 'rango:workout' %}">Workout</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'rango:add_category' %}">add category</a></li>
        {% endif %}
        {% endcomment %}
        <li><a href="{% url 'rango:activities' %}">Activities</a></li>
        <li><a href="{% url 'rango:nutrition' %}">Nutrition</a></li>
        <li><a href="{% url 'rango:report' %}">Report</a><br /></li>
       
    <div class="titles">
        <span class="center-title left">Macros</span>
        <span class="center-title right">Calories</span>
    </div>

    <div class="canvas-pos-left left">
        <div class="canvas"></div>
    </div>
    <div class="canvas-pos-right right">
        <div class="canvas-bar"></div>
    </div>
        
        <script> var macros = {{ nutrients_info | safe }};  
                 var calories = {{ calories_info | safe }};
        </script>
        <script src="{% static 'js/pie_chart_calories.js' %}"></script> 
        <script src="{% static 'js/calorie_bar.js' %}"></script>
    </div>
    
        <div class="footer">
            <div class="progress"> </div>
            <ul>
                <li class=footer><a href="{% url 'rango:profile' %}" class=footer>Profile</a></li>
                <li class=footer><a href="{% url 'rango:logout' %}" class=footer>Logout</a></li>         
            </ul>
        </div>
{% endblock %}

fitnessWebApp/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
    <div class="nav z-depth-0">
        <div class="section center">
            <h3 class="white-text center">- Welcome {{ user.username }} -</h3>
        </div>
    </div>

    <div class="progress"></div>
        {% comment %}    
        <li><a href="{% url 'rango:BMI' %}">Fat Percentage</a></li> 
        <li><a href="{% url 'rango:workout' %}">Workout</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'rango:add_category' %}">add category</a></li>
        {% endif %}
        {% endcomment %}
        <li><a href="{% url 'rango:exercises' %}">Activities</a></li>
        <li><a href="{% url 'rango:calories' %}">Nutrition</a></li>
        <li><a href="{% url 'rango:report' %}">Report</a><br /></li>
       
    <div class="titles">
        <span class="center-title left">Macros</span>
        <span class="center-title right">Calories</span>
    </div>

    <div class="canvas-pos-left left">
        <div class="canvas"></div>
    </div>
    <div class="canvas-pos-right right">
        <div class="canvas-bar"></div>
    </div>
        
        <script> var macros = {{ nutrients_info | safe }};  
                 var calories = {{ calories_info | safe }};
                 var activities = {{ activities_info | safe}};
        </script>
        <script src="{% static 'js/pie_chart_calories.js' %}"></script> 
        <script src="{% static 'js/calorie_bar.js' %}"></script>
    </div>
    
        <div class="footer">
            <div class="progress"> </div>
            <ul>
                <li class=footer><a href="{% url 'rango:profile' %}" class=footer>Profile</a></li>
                <li class=footer><a href="{% url 'rango:logout' %}" class=footer>Logout</a></li>         
            </ul>
        </div>
{% endblock %}

fitnessWebApp/templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
    <div class="nav z-depth-0">
        <div class="section center">
            <div class="header">
                <a href="{% url 'rango:homePage' %}"><span class="left">Home</span></a>
                <a href="{% url 'rango:logout' %}"><span class="right">Log Out</span></a>
            </div>
            <h3 class="white-text center">- {{ user.username }} -</h3>
        </div>
    </div>

        <div class="profile_display">
             <span class="info">Gender: {{ gender }}</span></span>
             <span class="info">BMR: {{ BMR }}</span></span>
             <span class="info">BMI: {{ BMI }}</span></span>
        </div>

        <div class="profile_edit">
            <form class="profile_form" id="activity_post_form" method="post" action= "{% url 'rango:profile' %}">
                {% csrf_token %}
                <span>Age:</span>
                <input type="number" placeholder={{ age }} name="age" id="age" size="10" />
                <br />

                <span>Weight:</span>
                <input type="number" name="weight" id="weight" size="10" placeholder={{ weight }} />
                <br />

                <span>Height:</span>
                <input type="number" name="height" id="height" size="10" placeholder={{ height }} />
                <br />

                <span>Goal:</span>
                <select name="goal" id="goal">
                    <option value="current">{{ goal }}</option>
                    <option value="bulk">BULK</option>
                    <option value="maintenance">MAINTENANCE</option>
                    <option value="fat loss">FAT LOSS</option>
                </select>
                <br />

                <input type="submit" name="submit" value="Edit" />
            </form> 
    </div>
{% endblock %}